os:
  - osx
language: swift
osx_image: xcode13.2
env:
  - PROJECT_NAME=CircularProgressView
install: swift package update
script:
  - xcodebuild build -sdk iphoneos -destination 'platform=iOS Simulator,name=iPhone 13 Pro Max' -scheme $PROJECT_NAME
